name: test

on:
  workflow_dispatch:
    inputs:
      envParam:
        type: choice
        description: Pick env to deploy to
        options:
        - dev
        - prod
        required: true

jobs:
  build_dev:
    if: ${{ inputs.envParam == 'dev' }}
    runs-on: ubuntu-latest
    env:
      RG: dev-rg
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo ${{ env.RG }}

  build_prod:
    if: ${{ inputs.envParam == 'prod' }}
    runs-on: ubuntu-latest
    env:
      RG: prod-rg
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo ${{ env.RG }}
