name: justBuild

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      envParam:
        type: choice
        description: Pick env to deploy to
        default: dev
        options:
        - dev
        - prd
        required: true

jobs:
  build_dev:
    if: ${{ inputs.envParam == 'dev' }}
    runs-on: ubuntu-latest
    environment: 
      name: dev
    env:
      User: ${{ secrets.USER }}
      location: ${{ vars.LOCATION }}
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo ${{ env.User }}
          echo ${{ vars.LOCATION }}
          echo Worked on ${{ inputs.envParam }}

  build_prod:
    if: ${{ inputs.envParam == 'prd' }}
    runs-on: ubuntu-latest
    environment: 
      name: prd
    env:
       User: ${{ secrets.USER }}
       location: ${{ vars.LOCATION }}
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo ${{ env.User }}
          echo ${{ vars.LOCATION }}
          echo Worked on ${{ inputs.envParam }}
