name: test

on:
  workflow_dispatch:
    inputs:
      envParam:
        type: choice
        description: Pick env to deploy to
        options:
        - dev
        - prd
        required: true

jobs:
  build_dev:
    if: ${{ inputs.envParam == 'dev' }}
    runs-on: ubuntu-latest
    env:
      User: ${{ secrets.USER }}
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo ${{ env.User }}

  build_prod:
    if: ${{ inputs.envParam == 'prd' }}
    runs-on: ubuntu-latest
    env:
       User: ${{ secrets.USER }}
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo ${{ env.User }}
