name: testWithSingleJob

on:
  workflow_dispatch:
    inputs:
      envParam:
        type: choice
        description: Pick env to deploy to
        options:
        - dev
        - prd
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.envParam }}
    env:
      User: ${{ secrets.USER }}
      location: ${{ vars.LOCATION }}
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo ${{ env.User }}
          echo ${{ vars.LOCATION }}
          echo ${{secrets.USER}} | sed 's/./& /g'
